### ISSUE TITLE
Is there a way to get decorator parameters?

### ISSUE THREAD

**Issue by YagoLopez** [artifacthealth/reflect-helper#3]
My use case is an ORM in typescript.

```typescript
class entity1 {

  @decorator1(parameter1)
  property1: string;

  @decorator2(parameter2)
  property2: number;

}
```

Is there a  way to get `parameter1` value, for example?
Thanks

**Comment by meirgottlieb** [comment]
You need to use an annotation as described in the documentation [here](http://artifacthealth.github.io/reflect-helper/). Also, take a look at the ODM that I built this library for, [hydrate-mongodb](https://github.com/artifacthealth/hydrate-mongodb), for additional examples.

**Comment by YagoLopez** [comment]
Thanks for the response. If I am not wrong I have to create a class as a decorator and the constructor parameters of the class will be the parameters of the decorator. Could you confirm it? Also Hydrate is a very interesting project. I take note for future posible uses.

**Comment by meirgottlieb** [comment]
Yes. That is correct. You create a class as an annotation. You then use [makeDecorator](http://artifacthealth.github.io/reflect-helper/globals.html#makedecorator) to turn that class into a decorator. The constructor arguments become the decorator arguments. When the decorator is applied to a class, the corresponding annotation is created and added to the class. It can then be retrieved using [getAnnotations[(http://artifacthealth.github.io/reflect-helper/classes/type.html#getannotations).

**Comment by YagoLopez** [comment]
Understood. Besides in my case the decorated property is a class that represents a column in a table of the database. Using decoration I can add metadata to a property to define columns attributes like type, size, nullable, etc. so it is very appropiated. Thanks again.
